
SHELL ?= $(DEFAULT_SHELL)

CPP ?= $(DEFAULT_CPP)
CPPFLAGS ?= $(DEFAULT_CPPFLAGS)

FC ?= $(DEFAULT_FC)
FFLAGS ?= $(DEFAULT_FFLAGS)

LDFLAGS ?= 

BIN_NAME ?= $(DEFAULT_BIN_NAME)
BIN_PREFIX ?= $(DEFAULT_BIN_PREFIX)
BIN_SUFFIX ?= $(DEFAULT_BIN_SUFFIX)

OPTIONS += -DDOUBLE_PRECISION
OPTIONS += -DPARALLEL
OPTIONS += -DLANDSLIDE
OPTIONS += -DSALINITY
OPTIONS += -DTEMPERATURE
OPTIONS += -DBUBBLE
OPTIONS += -DSEDIMENT
OPTIONS += -DVEGETATION
OPTIONS += -DINTEL
OPTIONS += -DBALANCE2D
OPTIONS += -DTWOLAYERSLIDE
OPTIONS += -DCORALREEF

HYPRE_FFLAGS ?= 
HYPRE_LDFLAGS ?= 
HYPRE_LIBS ?= 

